export const projects = [
  {
    id: 1,
    title: "React Ecommerce Website",
    cover: "",
    excerpt: "",
    tags: ["React", "Redux"],
    github: "",
    live: "",
    blog: "",
  },
  {
    id: 2,
    title: "Covid19 Tracker App",
    cover: "",
    excerpt: "",
    tags: ["React", "Redux", "API"],
    github: "",
    live: "",
    blog: "",
  },
  {
    id: 3,
    title: "StoryBook",
    cover: "",
    excerpt: "",
    tags: ["Node", "ejs"],
    github: "",
    live: "",
    blog: "",
  },
  {
    id: 4,
    title: "College Fest Website",
    cover: "",
    excerpt: "",
    tags: ["Node", "Ejs"],
    github: "",
    live: "",
    blog: "",
  },
]
